name: b_coin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase Packages
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  google_sign_in: ^6.2.2
  firebase_database: ^11.3.5
  # Animations & UI Enhancements
  lottie: ^3.2.0
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  introduction_screen: ^3.1.17
  url_launcher: ^6.3.1
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.5.2
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  syncfusion_flutter_charts: ^29.1.35
  fluttertoast: ^8.2.12
  dropdown_button2: ^2.3.9
  flutter_timer_countdown: ^1.0.7
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  http: ^1.4.0
  cached_network_image: 3.3.1 # ✅ Compatible with uuid ^3.x
  web3dart: ^2.5.4  # ⬅️ Yeh version uuid 3.x ke saath compatible hai
  uuid: ^3.0.6       # ⬅️ Force uuid version 3.x
  flutter_blurhash: ^0.9.0
  app_links: ^6.4.0
  flutter_secure_storage: ^9.2.4
#  walletconnect_flutter_v2:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"  # App Icon Path
  adaptive_icon_foreground: "assets/logo_adaptive_foreground.png"  # Only for Android Adaptive Icons
  adaptive_icon_background: "#ffffff"  # Background Color

flutter:
  uses-material-design: true

  assets:
    - assets/
dependency_overrides:
  walletconnect_flutter_v2:
    git:
      url: https://github.com/WalletConnect/flutter-walletconnect-v2.git
      ref: main

