// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO_VQLfH2ZtaSiOQNRClLlPNPUTXtnStw',
    appId: '1:558129311814:web:0890faf4b461daf6b7da47',
    messagingSenderId: '558129311814',
    projectId: 'b-coin-c5eb6',
    authDomain: 'b-coin-c5eb6.firebaseapp.com',
    storageBucket: 'b-coin-c5eb6.firebasestorage.app',
    measurementId: 'G-VNGNYDY16Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgtLmox30Wlv3s-o2rM3u_B6-V9ZvwGX0',
    appId: '1:558129311814:android:c8d92e52c9a5b381b7da47',
    messagingSenderId: '558129311814',
    projectId: 'b-coin-c5eb6',
    storageBucket: 'b-coin-c5eb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX7fnNf2GeeKzEuSWXv0IwkCH6CNRLn1U',
    appId: '1:558129311814:ios:05d09f86d775acb0b7da47',
    messagingSenderId: '558129311814',
    projectId: 'b-coin-c5eb6',
    storageBucket: 'b-coin-c5eb6.firebasestorage.app',
    iosBundleId: 'com.example.bCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX7fnNf2GeeKzEuSWXv0IwkCH6CNRLn1U',
    appId: '1:558129311814:ios:05d09f86d775acb0b7da47',
    messagingSenderId: '558129311814',
    projectId: 'b-coin-c5eb6',
    storageBucket: 'b-coin-c5eb6.firebasestorage.app',
    iosBundleId: 'com.example.bCoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO_VQLfH2ZtaSiOQNRClLlPNPUTXtnStw',
    appId: '1:558129311814:web:d52b025dfe8b924eb7da47',
    messagingSenderId: '558129311814',
    projectId: 'b-coin-c5eb6',
    authDomain: 'b-coin-c5eb6.firebaseapp.com',
    storageBucket: 'b-coin-c5eb6.firebasestorage.app',
    measurementId: 'G-3E66DEP1RB',
  );
}
